CREATE TABLE IF NOT EXISTS records(
npi_number                               INTEGER NOT NULL PRIMARY KEY,
created_epoch                            INTEGER NULL,
enumeration_type                         VARCHAR(5) NULL,
last_updated_epoch                       INTEGER NULL,
organization_name                        VARCHAR(32) NULL,
organizational_subpart                   VARCHAR(2) NULL,
parent_organization_legal_business_name  VARCHAR(32) NULL,
enumeration_date                         DATE NULL,
last_updated                             DATE NULL,
organization_status                      VARCHAR(1) NULL,
auth_official_first_nam                  VARCHAR(8) NULL,
auth_official_last_name                  VARCHAR(5) NULL,
auth_official_telephone_number           INTEGER NULL,
auth_official_title_or_position          VARCHAR(5) NULL,
auth_official_name_prefix                VARCHAR(3) NULL,
auth_official_credential                 VARCHAR(3) NULL,
addr_practice_country_code               VARCHAR(2) NULL,
addr_practice_country_name               VARCHAR(16) NULL,
addr_practice_address_type               VARCHAR(8) NULL,
addr_practice_1                          VARCHAR(64) NULL,
addr_practice_2                          VARCHAR(32) NULL,
addr_practice_city                       VARCHAR(22) NULL,
addr_practice_state                      VARCHAR(2) NULL,
addr_practice_postal_code                INTEGER NULL,
addr_practice_telephone_number           VARCHAR(12) NULL,
addr_mail_country_code                   VARCHAR(2) NULL,
addr_mail_country_name                   VARCHAR(16) NULL,
addr_mail_address_type                   VARCHAR(8) NULL,
addr_mail_1                              VARCHAR(64) NULL,
addr_mail_2                              VARCHAR(32) NULL,
addr_mail_city                           VARCHAR(22) NULL,
addr_mail_state                          VARCHAR(2) NULL,
addr_mail_postal_code                    INTEGER NOT NULL,
addr_mail_telephone_number               VARCHAR(12) NULL,
primary_taxonomy_code                    VARCHAR(10) NULL,
primary_taxonomy_taxonomy_group          VARCHAR(35) NULL,
primary_taxonomy_desc                    VARCHAR(7) NULL,
primary_taxonomy_state                   VARCHAR(30) NULL,
primary_taxonomy_license                 VARCHAR(30) NULL
)